Actions:
  - Name: application-signals:BatchGetServiceLevelObjectiveBudgetReport
  - Name: application-signals:CreateServiceLevelObjective
  - Name: application-signals:DeleteServiceLevelObjective
  - Name: application-signals:GetService
  - Name: application-signals:GetServiceLevelObjective
  - Name: application-signals:ListServiceDependencies
  - Name: application-signals:ListServiceDependents
  - Name: application-signals:ListServiceLevelObjectives
  - Name: application-signals:ListServiceOperations
  - Name: application-signals:ListServices
  - Name: application-signals:ListTagsForResource
  - Name: application-signals:StartDiscovery
  - Name: application-signals:TagResource
  - Name: application-signals:UntagResource
  - Name: application-signals:UpdateServiceLevelObjective

  # actions with no corresponding API
  - Name: application-signals:BatchUpdateExclusionWindows
  - Name: application-signals:DeleteGroupingConfiguration
  - Name: application-signals:Link
  - Name: application-signals:ListAuditFindings
  - Name: application-signals:ListGroupingAttributeDefinitions
  - Name: application-signals:ListObservedEntities
  - Name: application-signals:ListServiceLevelObjectiveExclusionWindows
  - Name: application-signals:ListServiceStates
  - Name: application-signals:PutGroupingConfiguration
