Actions:
  - Name: application-autoscaling:DeleteScalingPolicy
  - Name: application-autoscaling:DeleteScheduledAction
  - Name: application-autoscaling:DeregisterScalableTarget
  - Name: application-autoscaling:DescribeScalableTargets
  - Name: application-autoscaling:DescribeScalingActivities
  - Name: application-autoscaling:DescribeScalingPolicies
  - Name: application-autoscaling:DescribeScheduledActions
  - Name: application-autoscaling:PutScalingPolicy
  - Name: application-autoscaling:PutScheduledAction
  - Name: application-autoscaling:RegisterScalableTarget

  # APIs without an IAM action
  - Name: application-autoscaling:ListTagsForResource
  - Name: application-autoscaling:TagResource
  - Name: application-autoscaling:UntagResource
