Actions:

  # APIs without an IAM action
  - Name: application-cost-profiler:DeleteReportDefinition
  - Name: application-cost-profiler:GetReportDefinition
  - Name: application-cost-profiler:ImportApplicationUsage
  - Name: application-cost-profiler:ListReportDefinitions
  - Name: application-cost-profiler:PutReportDefinition
  - Name: application-cost-profiler:UpdateReportDefinition
