Actions:

  # actions with no corresponding API
  - Name: application-transformation:GetGroupingAssessment
  - Name: application-transformation:GetPortingCompatibilityAssessment
  - Name: application-transformation:GetPortingRecommendationAssessment
  - Name: application-transformation:GetRuntimeAssessment
  - Name: application-transformation:PutLogData
  - Name: application-transformation:PutMetricData
  - Name: application-transformation:StartGroupingAssessment
  - Name: application-transformation:StartPortingCompatibilityAssessment
  - Name: application-transformation:StartPortingRecommendationAssessment
  - Name: application-transformation:StartRuntimeAssessment
