Actions:
  - Name: codeguru-security:BatchGetFindings
  - Name: codeguru-security:CreateScan
  - Name: codeguru-security:CreateUploadUrl
  - Name: codeguru-security:GetAccountConfiguration
  - Name: codeguru-security:GetFindings
  - Name: codeguru-security:GetMetricsSummary
  - Name: codeguru-security:GetScan
  - Name: codeguru-security:ListFindingsMetrics
  - Name: codeguru-security:ListScans
  - Name: codeguru-security:ListTagsForResource
  - Name: codeguru-security:TagResource
  - Name: codeguru-security:UntagResource
  - Name: codeguru-security:UpdateAccountConfiguration

  # actions with no corresponding API
  - Name: codeguru-security:DeleteScansByCategory
  - Name: codeguru-security:ListFindings
