Actions:

  # actions with no corresponding API
  - Name: codeguru-security:BatchGetFindings
  - Name: codeguru-security:CreateScan
  - Name: codeguru-security:CreateUploadUrl
  - Name: codeguru-security:DeleteScansByCategory
  - Name: codeguru-security:GetScan
  - Name: codeguru-security:ListFindings
  - Name: codeguru-security:ListScans
  - Name: codeguru-security:UpdateAccountConfiguration
