Actions:
  - Name: emr-serverless:CancelJobRun
  - Name: emr-serverless:CreateApplication
  - Name: emr-serverless:DeleteApplication
  - Name: emr-serverless:GetApplication
  - Name: emr-serverless:GetJobRun
  - Name: emr-serverless:ListApplications
  - Name: emr-serverless:ListJobRuns
  - Name: emr-serverless:ListTagsForResource
  - Name: emr-serverless:StartApplication
  - Name: emr-serverless:StartJobRun
  - Name: emr-serverless:StopApplication
  - Name: emr-serverless:TagResource
  - Name: emr-serverless:UntagResource
  - Name: emr-serverless:UpdateApplication

  # APIs without an IAM action
  - Name: emr-serverless:GetDashboardForJobRun
