Actions:

  # actions with no corresponding API
  - Name: geo-routes:CalculateIsolines
  - Name: geo-routes:CalculateRouteMatrix
  - Name: geo-routes:CalculateRoutes
  - Name: geo-routes:OptimizeWaypoints
  - Name: geo-routes:SnapToRoads
